// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA810SVS3xrQzIbfMEkYC-hwgVRXiH2Pho',
    appId: '1:933811200183:web:19e12ef6f828c6bbd62d32',
    messagingSenderId: '933811200183',
    projectId: 'danlens',
    authDomain: 'danlens.firebaseapp.com',
    storageBucket: 'danlens.firebasestorage.app',
    measurementId: 'G-GTQP41GJK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlwGa60cXzHuxX_YvZfiH4EPj7cVio2c',
    appId: '1:933811200183:android:0744e407beced2b4d62d32',
    messagingSenderId: '933811200183',
    projectId: 'danlens',
    storageBucket: 'danlens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFdOVLeMiRR7tY4DjT9KPABWvMpIlBZM',
    appId: '1:933811200183:ios:115cd9ceca22f6aad62d32',
    messagingSenderId: '933811200183',
    projectId: 'danlens',
    storageBucket: 'danlens.firebasestorage.app',
    iosBundleId: 'com.example.danlens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFdOVLeMiRR7tY4DjT9KPABWvMpIlBZM',
    appId: '1:933811200183:ios:115cd9ceca22f6aad62d32',
    messagingSenderId: '933811200183',
    projectId: 'danlens',
    storageBucket: 'danlens.firebasestorage.app',
    iosBundleId: 'com.example.danlens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA810SVS3xrQzIbfMEkYC-hwgVRXiH2Pho',
    appId: '1:933811200183:web:9d991186d5aefe20d62d32',
    messagingSenderId: '933811200183',
    projectId: 'danlens',
    authDomain: 'danlens.firebaseapp.com',
    storageBucket: 'danlens.firebasestorage.app',
    measurementId: 'G-QBPSFNETBV',
  );
}
